### ISSUE TITLE
Ignore SIGURG

### ISSUE THREAD

**Issue by ehrlich-b** [datto/kmod-dblock#1]
SIGURG is [(ab)used](https://github.com/golang/go/blob/master/src/runtime/signal_unix.go#L65) by the golang runtime for its [non-cooperative goroutine pre-emption](https://go.googlesource.com/proposal/+/master/design/24543-non-cooperative-preemption.md) implementation. 

These signals are caught in dblock's interruptible wait handler:
```
Feb 27 23:35:54 behrlich-ubuntu kernel: [ 2723.703537] dblock:[3884] error userspace: Got signal 23 waiting for cv: 22
Feb 27 23:35:54 behrlich-ubuntu kernel: [ 2723.703539] dblock:[3884] error userspace: userspace cv_wait for block_cv exited because of signal, unlocking mutex, returning error to ioctl, signal_number 23: -4
```
Which causes my driver to receive EINTR and crash.

SIGURG should simply be ignored.

**Comment by nixomose** [comment]
okay, I can do that. gimme a bit.

**Comment by nixomose** [comment]
okay give this a try.

there's two sides to the kernel module, and I ignore SIGURGs on the side that userspace is calling, so hopefully that will cover the cases you're running into.
lemme know if something else comes up.
I treat all signals as problems, so other things may come up like this.
I forget, but I think the signal is sent back to userspace, not sure.
if not, you can see if the return code is -EINTR and if so, just go back and call dblock_operation_block_for_request again.
but better to not bounce back and forth between userspace and kernel for no reason, it will just slow things down.

but there are signals I do want to get back to userspace, so I don't want to filter everything by default.

anyway, give this a go.
ha ha. go.

**Comment by ehrlich-b** [comment]
My test is passing cleanly this morning after this change. I also updated to retry on EINTR so legit interrupts should be handled gracefully. Thanks for the ultra quick turnaround 😄
