### ISSUE TITLE
Only one blocker is terminated

### ISSUE THREAD

**Issue by ehrlich-b** [datto/kmod-dblock#3]
I am parallelizing my user space integration. It works! I see both my threads getting work from the kernel. The problem is that when I signal destroy (using destroy device by ID) only one of my threads is halted. The other thread gets stuck sleeping in `block for request`.

Let me know if there's any other info I can provide.

**Comment by ehrlich-b** [comment]
Pushed up my currently non-working code here https://github.com/adotout/copyondemand/blob/kmod-dblock-parallel/dblock.go#L69 in case it helps. So I'll see in the log something like:
```
[While working]
Got a read request on 1
Got a read request on 2
Got a read request on 1
Got a read request on 2
[After I ^C]
Got a request to stop on 1, stopping
```
And nothing else. So presumably the other thread is still in the ioctl responding to the previous read or write, being blocked by the kernel.

**Comment by nixomose** [comment]
very cool, I figured it should work, but I never actually tried it myself yet. :-)

so yeah, the destroy is the one thing I knew wouldn't work correctly, I'll go fix that.

**Comment by nixomose** [comment]
okay I just committed a change, give it a go.
I think it will work but I don't actually have any multithreaded test programs to test it out with [yet].
so while I'm doing that, you can try it out also.

if you have problems or it doesn't appear to work correctly, do this:
echo 1 > /sys/module/dblock/parameters/debug_logs
and send me your kern.log after you try and destroy.

**Comment by nixomose** [comment]
oh also, something weird about the PRs... I had a change in my nixomose fork that datto one did not have, I assume you had that though otherwise you'd still be having signal problems.
anyway, I merged both changes so the latest is in both repos datto's and mine.

**Comment by ehrlich-b** [comment]
I put this through its paces today and couldn't come up with an issue. I tried turning user space up to 20 threads and did a variety of spin ups/spins down. In all cases, all threads get properly signaled to tear down. I also noticed that all the threads are signaled before the "destroy by id" syscall returns - not sure if that was on purpose but I like it 😄

Thanks!!

**Comment by nixomose** [comment]
yeah it's designed to work that way. It sends the notification and waits a tiny bit for userspace to grab it before it goes on to the next one, so yeah, it 'should' all be done (all userspaces should have been unblocked) by the time you get the destroy call back.
But it's a best effort thing, if the userspace guy is off doing work he won't be around to get the signal, and it will skip him.
but at that point the device is already flagged as shutting down so when userspace comes back with a response for whatever it was doing it will get an error, and not block. so you should be good no matter what.

if you're good, I'll close this.

**Comment by ehrlich-b** [comment]
Yep, if you're good I'm good 🥳
